// create a class game and let the user guess the number, also give hint each time they fail like "it is bigger" or "it is smaller"
// the user will only win the game if the number is equal to the random number generated by the computer

import java.util.Random;
import java.util.Scanner;

class Game {
    private final int randNum;
    private int guessNum;
    private int noOfGuess;

    public Game() {
        Random random = new Random();
        this.randNum = random.nextInt(100);

        noOfGuess = 0;
    }

    public void setInputNumber(int num) {
        this.guessNum = num;
        noOfGuess++;
    }

    public boolean isCorrectNumber() {
        if (guessNum < randNum) {
            System.out.println("Guess a bit bigger");
        }
        if (guessNum > randNum) {
            System.out.println("Guess a bit smaller");
        }
        return this.guessNum == this.randNum;
    }

    public int getNoOfGuess() {
        return this.noOfGuess;
    }
}

public class guessTheNumber {
    public static void main(String[] args) {
        Scanner inp = new Scanner(System.in);

        Game game;
        game = new Game();

        System.out.print("Guess a number : ");
        int num = inp.nextInt();

        game.setInputNumber(num);
        boolean gameOver = game.isCorrectNumber();

        while (!gameOver) {
            System.out.println();
            System.out.print("Guess a number again : ");
            num = inp.nextInt();
            game.setInputNumber(num);
            gameOver = game.isCorrectNumber();
        }

        System.out.println();

        System.out.println("Congratulations, You guessed the correct number");
        System.out.println("No of guess : " + game.getNoOfGuess());
    }
}
